//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCDoanhThuThang
    {
        public int MaTau { get; set; }
        public int MaKH { get; set; }
        public int MaViTri { get; set; }
        public string GiaVe { get; set; }
        public Nullable<int> Thang { get; set; }
    
        public virtual CT_LichTau_VeTau CT_LichTau_VeTau { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
