//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_GaTrungGian
    {
        public int MaGaTrungGian { get; set; }
        public Nullable<int> MaLichTau { get; set; }
        public Nullable<int> MaGa { get; set; }
        public string ThoiGianDung { get; set; }
    
        public virtual GaTau GaTau { get; set; }
        public virtual LichTau LichTau { get; set; }
    }
}
