//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_LichTau_VeTau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CT_LichTau_VeTau()
        {
            this.VeTaus = new HashSet<VeTau>();
        }
    
        public int MaViTri { get; set; }
        public Nullable<int> MaLichTau { get; set; }
        public bool DaDat { get; set; }
    
        public virtual LichTau LichTau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VeTau> VeTaus { get; set; }
    }
}
