//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichTau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichTau()
        {
            this.CT_GaTrungGian = new HashSet<CT_GaTrungGian>();
            this.CT_LichTau_VeTau = new HashSet<CT_LichTau_VeTau>();
            this.VeTaus = new HashSet<VeTau>();
        }
    
        public int MaLichTau { get; set; }
        public Nullable<int> MaTau { get; set; }
        public Nullable<int> MaGaDi { get; set; }
        public Nullable<int> MaGaDen { get; set; }
        public System.DateTime NgayDi { get; set; }
        public string ThoiGianDi { get; set; }
        public string ThoiGianDen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_GaTrungGian> CT_GaTrungGian { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_LichTau_VeTau> CT_LichTau_VeTau { get; set; }
        public virtual DSTau DSTau { get; set; }
        public virtual GaTau GaTau { get; set; }
        public virtual GaTau GaTau1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VeTau> VeTaus { get; set; }
    }
}
