//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLyGheTau
    {
        public int MaQLGhe { get; set; }
        public Nullable<int> MaTau { get; set; }
        public Nullable<int> MaToa { get; set; }
        public string TenViTri { get; set; }
    
        public virtual DSTau DSTau { get; set; }
        public virtual ToaTau ToaTau { get; set; }
    }
}
